### ISSUE TITLE
C2W

### ISSUE THREAD

**Issue by siddhantbapna** [iamankitdwivedi/TicTacToe-AI#2]
Hey Ankit,
I am Siddhant Bapna from Udaipur Rajasthan, I secured AIR-2 in C2W and it's nice to meet you.

Firstly, Congratulation for AIR-1 in C2W.

I want to talk to you, can we have a chat or a call if you are free ?

**Comment by dwivedi-ai** [comment]
Hi Siddhant,
Congratulations for securing AIR-2 🎉👏
It's a pleasure to meet you. Sure we can have a chat. Please let me know about your preferred social media platform for communication and your account so we can connect.

**Comment by siddhantbapna** [comment]
Are you comfortable with google meet or skype ?

**Comment by iamankitdwivedi** [comment]
Yes, add me on Skype.
: https://join.skype.com/invite/v2sMXHl9K5T3
